# Generated by Django 5.1 on 2024-08-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiagnosticoGestacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brinco", models.CharField(max_length=20)),
                ("data_cobertura", models.DateField()),
                ("data_diagnostico", models.DateField()),
                ("reprodutor", models.CharField(max_length=100)),
                ("ultimo_parto", models.DateField()),
                ("dias_gestacao", models.IntegerField()),
                ("resultado", models.CharField(max_length=20)),
                ("observacao", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
